apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-secret-json
spec:
  refreshInterval: 60s
  secretStoreRef:
    name: aws-store
    kind: SecretStore
  target:
    name: myapp-creds
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: "/dev/myapp/db-creds"
