apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-secret-tpl
spec:
  refreshInterval: 60s
  secretStoreRef:
    name: aws-store
    kind: SecretStore
  target:
    name: my-secret-tpl
    creationPolicy: Owner
    template:
      data:
        config: |
          datasources:
          - name: Graphite
            type: graphite
            access: proxy
            url: http://localhost:8080
            password: "{{ .password }}"
            user: "{{ .username }}"

  dataFrom:
  - extract:
      key: "/dev/myapp/db-creds"
