apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-secret
spec:
  refreshInterval: 60s
  secretStoreRef:
    name: aws-store
    kind: SecretStore
  target:
    name: my-secret
    creationPolicy: Owner
    deletionPolicy: Merge
  data:
  - secretKey: password_current
    remoteRef:
      key: "my-password"
      version: "AWSCURRENT"
  - secretKey: password_previous
    remoteRef:
      key: "my-password"
      version: "AWSPREVIOUS"

